### ISSUE TITLE
Can UGUI components be edited?

### ISSUE THREAD

**Issue by sam8890** [BattlehubCode/RTE_Docs#108]
I want to create a UI layout designer similar to the UGUI designer in Unity. For example, using the mouse to drag and place images, control their positions, and sizes, and also have alignment guides, snapping functionality, etc., when dragging."

**Comment by BattlehubCode** [comment]
Runtime Editor supports some simple UGUI controls and components like RectTransform out of box

![image](https://github.com/user-attachments/assets/5ee013c7-7038-49f9-8c9f-6e090c93c0da)
