### ISSUE TITLE
[Runtime Transform Handles] Unable to move camera

### ISSUE THREAD

**Issue by weilifang25** [BattlehubCode/RTE_Docs#117]
Thank you for your reply, but it does not solve my problem. I want to ask why I can't move the main camera? I need to find a problem in the scene, click a button, and then move the camera so that the object is in the center of the screen. Now the problem is that the camera position is fixed and cannot be changed.

**Comment by BattlehubCode** [comment]
You can move camera using following code:

```
var sceneComponent = FindObjectOfType<RuntimeSceneComponent>();
sceneComponent.SetCameraPositionAndPivot(
            position: new Vector3(0, 10, 10),
            pivot:    new Vector3(0, 10, 0));
```           

To gain full control over main camera, you can do the following:

1. Create new unity scene
2. Click Tools -> Runtime Handles -> Create
3. Replace the RuntimeSceneComponent and RuntimeSceneInput as shown in the image below.

![Untitled](https://github.com/user-attachments/assets/cb160bc5-8d65-478c-83bf-7c25b3e8e1e5)
