### ISSUE TITLE
Run the rotation scene

### ISSUE THREAD

**Issue by weilifang25** [BattlehubCode/RTE_Docs#120]
After clicking play to run, keep the right mouse button and middle mouse button function. The demo scenario does not have such a feature, nor does the documentation find a similar method

**Comment by BattlehubCode** [comment]
I'm not sure I understand question but check OnPlaymodeStateChanged metod. 
![image](https://github.com/user-attachments/assets/25b113fc-c804-4c3b-b1e8-39f986e31703)

Maybe you just need to keep m_editor & m_components enabled after you enter play model
![image](https://github.com/user-attachments/assets/07a3f141-b96b-43a7-b439-cb80e6ef06a2)

![image](https://github.com/user-attachments/assets/18f12bf2-a04d-4a0f-b585-91cc3c6ce755)

https://github.com/user-attachments/assets/ccf838f4-d6f9-474a-a9ab-1114dedd9f80

**Comment by weilifang25** [comment]
Your video is what I need. I'll try it.

**Comment by weilifang25** [comment]
The mouse function is available. Can you help me with my problem? After clicking the play button, the three coordinate axes are no longer displayed when clicking on the object.

**Comment by weilifang25** [comment]
My ultimate goal is to make the three-coordinate axis disappear when clicking on the object after the play is run.

**Comment by BattlehubCode** [comment]
You mean this ?

![image](https://github.com/user-attachments/assets/0da80453-49c0-4799-9a30-51ae557b1ccc)

![image](https://github.com/user-attachments/assets/6afc733d-f57f-413b-8b93-774889f83db0)

**Comment by BattlehubCode** [comment]
You mean this?

![image](https://github.com/user-attachments/assets/294bab3f-a4f3-48e8-bd1f-b635718145ce)

![image](https://github.com/user-attachments/assets/44de33ea-1ab8-46fa-8ff6-dabd5cf885ba)
