### ISSUE TITLE
Click the play button, and the three coordinate axes will no longer be displayed.

### ISSUE THREAD

**Issue by weilifang25** [BattlehubCode/RTE_Docs#122]
The mouse function is available. Can you help me with my problem? After clicking the play button, the three coordinate axes are no longer displayed when clicking on the object.

**Comment by weilifang25** [comment]
Because it is in the running state, clicking on the object displays the three coordinate axes, which greatly affects the interaction with the object

**Comment by BattlehubCode** [comment]
So when in play mode you want to hide axes or show them?

**Comment by BattlehubCode** [comment]
Maybe you are looking for this :) ?

![image](https://github.com/user-attachments/assets/37952e4d-9716-4ab1-a698-347acb3ca01f)

![image](https://github.com/user-attachments/assets/46df4b6b-3dec-49b5-86ec-798e154b04be)

**Comment by weilifang25** [comment]
Do not display the three coordinate axes

**Comment by weilifang25** [comment]
> 也许您正在寻找这个？
> 
> ![图像](https://private-user-images.githubusercontent.com/15802443/364338019-37952e4d-9716-4ab1-a698-347acb3ca01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDY0ODMsIm5iZiI6MTcyNTQ0NjE4MywicGF0aCI6Ii8xNTgwMjQ0My8zNjQzMzgwMTktMzc5NTJlNGQtOTcxNi00YWIxLWE2OTgtMzQ3YWNiM2NhMDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNzNjY2Q4OWZiMTExOWQwODhlMDY1MWE0NmNmM2QxMzQ1MDZjMTM0NGZhNjc0ZWU0YTllZjBhMjdhMDFhNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tY9_qqzHpQ3_nBP8SB61q733xzJL9muc4JJ3R0OzS64)
> 
> ![图像](https://private-user-images.githubusercontent.com/15802443/364337751-46df4b6b-3dec-49b5-86ec-798e154b04be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDY0ODMsIm5iZiI6MTcyNTQ0NjE4MywicGF0aCI6Ii8xNTgwMjQ0My8zNjQzMzc3NTEtNDZkZjRiNmItM2RlYy00OWI1LTg2ZWMtNzk4ZTE1NGIwNGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEwMzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjQ4OGRmYmU0ZDkwODMyMzQyN2Y5NzY4Njc0N2EzMmZkY2RhNDcyNTI2M2ZlZjJkNjY5MTAzNmY3NDFmY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WOso6KN5v6ZOnklFKuVhEv1RPl-Cx3DsJCRLejY96T4)

In which class is this method located?

**Comment by BattlehubCode** [comment]
![364294622-25b113fc-c804-4c3b-b1e8-39f986e31703](https://github.com/user-attachments/assets/57d3630c-12d8-4245-8c7a-df8b4e605e20)

**Comment by weilifang25** [comment]
Mine is different from yours?
![20240904_144359](https://github.com/user-attachments/assets/79d0596e-6695-4d38-8fb4-9d6e0b309452)

**Comment by weilifang25** [comment]
How to hide three axes after play run

**Comment by BattlehubCode** [comment]
Add this code to OnPlaymodeStateChanged

![image](https://github.com/user-attachments/assets/b3cd84bb-98c0-4ee8-8809-c7656657103a)

![image](https://github.com/user-attachments/assets/2dbeafa8-a8b0-4083-a82f-3025c8c78447)

and you will get this

![image](https://github.com/user-attachments/assets/1f1c23f5-f8ce-4cf6-b1bd-d076cb4dce0d)

**Comment by weilifang25** [comment]
I got it. I really appreciate your help

**Comment by BattlehubCode** [comment]
```
   protected virtual void OnPlaymodeStateChanged()
   {
       var runtimeToolsInput = FindObjectOfType<RuntimeToolsInput>(true);
       runtimeToolsInput.gameObject.SetActive(!Editor.IsPlaying);

       IRTE rte = IOC.Resolve<IRTE>();
       if (Editor.IsPlaying)
       {
           rte.Tools.Current = RuntimeTool.None;
       }
 
       if (m_components != null)
       {
          // m_components.SetActive(!Editor.IsPlaying);
       }
       if (m_ui != null)
       {
           m_ui.SetActive(!Editor.IsPlaying);
       }
       if(m_prefabSpawnPoints != null)
       {
           m_prefabSpawnPoints.SetActive(!Editor.IsPlaying);
       }
       if(m_stop != null)
       {
           m_stop.gameObject.SetActive(Editor.IsPlaying);
       }
       if(m_editorCamera != null)
       {
           //m_editorCamera.SetActive(!Editor.IsPlaying);
       }
       if(m_gameCamera != null)
       {
           m_gameCamera.SetActive(Editor.IsPlaying);
       }
   }
   ```
