### ISSUE TITLE
WebGL Build Failed :  'UnityEngine.PhysicsMaterialCombine' is declared in another module 

### ISSUE THREAD

**Issue by playdual** [BattlehubCode/RTE_Docs#123]
Hello.
Unity Version: 2022.3.44f1 / 2022.3.19f1
After changing the platform to WebGL, no separate packages were installed.

There is only a basic RTÉditor within the scene.
When you run a build with WebGL (Clean Build, Build and Run...), the build fails with an error as shown below.

There was no build failure before installing Runtime editor.

However, when I build RuntimeEditor immediately after installing it, I get an error.

I built Runtime Editor right after I imported it as a package manager. 

I get a build error even if I don't use Runtime Editor for the scene.

Just installing runtime editor in an empty scene will get a WebGL build error.

I've tried it on other computers, and the results are the same.

The asset was purchased on September 2nd.

![image](https://github.com/user-attachments/assets/849ee5af-df44-4999-8041-459ee08c5f3b)

![11](https://github.com/user-attachments/assets/02440e57-4666-451d-b8d8-5dba2f961502)

![3333](https://github.com/user-attachments/assets/3f96ba1a-b697-4cf2-9ca0-6edcf4efad7e)

below: empty Scene, Only Import Runtime Editor and then Build

![2222](https://github.com/user-attachments/assets/789a689d-ac97-45d0-8b65-85ff0fff6b37)

**Comment by BattlehubCode** [comment]
Hi,

Click "tools > runtime asset database > build all" from the main menu after switching to webgl platform in Unity editor. After this the build should run without issues.
 
https://github.com/BattlehubCode/RTE_Docs?tab=readme-ov-file#build-all

I'm aware of this, it seems to have started happening recently. I will try to fix it in one of the next releases.

Best regards, 
Vadim

**Comment by BattlehubCode** [comment]
Fixed in Runtime Editor 4.4.2

**Comment by playdual** [comment]
thx u r help.
