### ISSUE TITLE
Design Mode or Play Mode Selection

### ISSUE THREAD

**Issue by bryansq2nt** [BattlehubCode/RTE_Docs#125]
In the first View the RTE just show an Edit button when i click it it sends me to editors mode, like Unity interface, what i want to do is having to buttons at the first view, One Edit button that works like it is working now, just sending me to the Editor mode and i want to have another one, a Play button that just send me to play mode without being able to edit anything
![Screenshot 2024-09-10 211149](https://github.com/user-attachments/assets/5e44cb32-13de-43b9-be13-cdf8c17dfacf)

**Comment by BattlehubCode** [comment]
Example:

[Scene34 - Edit & Play.zip](https://github.com/user-attachments/files/17117294/Scene34.-.Edit.Play.zip)
