### ISSUE TITLE
Unity C# Void Start

### ISSUE THREAD

**Issue by bryansq2nt** [BattlehubCode/RTE_Docs#128]
I'm just creating a basic script, it supposed to instantiate a Cube when the Void Start is called, but the Void Start it's being called just when I pressed play in Unity but what I was expecting was the Void Start to be called when I pressed play in the Run Time Editor mode, so basically my Void Start it's being called twice, first time when I press play in Unity Editor and when I press play in Run Time Editor mode, I attached a picture where you can see how's the cube already instantiated without even press play and also here's the code:

```using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BasicScript : MonoBehaviour
{
    public GameObject exampleCube;
    void Start()
    {
        Debug.Log("Just Instantiated");
        GameObject newObj = Instantiate(exampleCube);
    }


}



![Screenshot 2024-09-18 203055](https://github.com/user-attachments/assets/5ca98958-1544-4986-9ddf-dfb8cb7cefbb)

**Comment by BattlehubCode** [comment]
Hi, I know 2 workarounds, but it's not exactly what you are asking about (there is currently no easy way to disable the Start method)

1- Use this option https://github.com/BattlehubCode/RTE_Docs?tab=readme-ov-file#time-scale.

This will disable the Update method in edit mode. And you can compare the timeline to 0 in the Start method to see what mode the editor is currently in.

2. If you want to make your UI components not interactable in edit mode, you can use the CanvasGroup component and toggle the CanvasGroup.interactable property depending on the editor mode.

https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/class-CanvasGroup.html
