### ISSUE TITLE
Q. Custom Component Question

### ISSUE THREAD

**Issue by playdual** [BattlehubCode/RTE_Docs#129]
Hello.
I posted a question because I had a few questions while making custom components.

Q1. 
![image](https://github.com/user-attachments/assets/cdcbb26c-c6e5-4664-bd5e-c59684764d2d)
If you look at the image I posted on top,
The "Image Name" part is a modifiable area (defined as string) and I want to make it impossible to modify (InputField -> Text) in the inspector, what should I do?

Or is it possible to keep InputField, and only make modifications impossible?

Q2.
![image](https://github.com/user-attachments/assets/af220d8f-53aa-4ab3-a674-994d3f2b4084)
Is it possible to block the File select (Right Circle) button from view (or remove it)

Q3.
Can I call the function I want, not the function that is basically defined when I press the select button?

For example, if you press the button to select the image above (pictured in question 2), you can only import the image file within the project. But I want to connect the function of importing files from the local PC.

**Comment by BattlehubCode** [comment]
Q1, 
there is not good way to do this, I'll think how to do it better and add in one of the next releases
Q2,
do you want to block it only in JintComponent or everywhere?
Q3,
It is possible to override which dialog (one per Type) the "Right Circle" button opens.

For example, to register your dialog that will allow you to import texture from your PC, you should do it like this:
wm.RegisterWindow("SelectTexture", .....

For Texuture2D -> wm.RegisterWindow("SelectTexture2D", .....
For Sprite -> wm.RegisterWindow("SelectSprite", ...


```
using Battlehub.RTCommon;
using Battlehub.RTEditor;
using Battlehub.UIControls.MenuControl;
using UnityEngine;

namespace Test
{
    [MenuDefinition]
    public class RegisterCustomWindow : EditorExtension
    {
        [SerializeField]
        private GameObject m_prefab = null;

        [SerializeField]
        private Sprite m_icon = null;
		
        [SerializeField]
        private string m_header = "Custom";

        [SerializeField]
        private bool m_isDialog = true;
		
        [SerializeField]
        private int m_maxWindows = -1;

        protected override void OnInit()
        {
            base.OnInit();

            IWindowManager wm = IOC.Resolve<IWindowManager>();
            wm.RegisterWindow("SelectTexture", m_header, m_icon, m_prefab, m_isDialog, m_maxWindows);
        }
    }
}
```

See the SelectObjectViewModel.cs example for how to implement this dialog. 
The only requirement is to implement an object selection dialog and set the selected object when closing the dialog.

```
using Battlehub.RTEditor;
using Battlehub.RTEditor.ViewModels;
using System;
using UnityWeld.Binding;

namespace Test.ViewModels
{
    [Binding]
    public class CustomViewModel : ViewModel, ISelectObjectDialog
    {
        public Type ObjectType 
        {
            get;
            set;
        }

        public bool IsNoneSelected
        {
            get;
            private set;
        } 

        public UnityEngine.Object SelectedObject
        {
            get;
            private set;
        }

        protected override void Start()
        {
            base.Start();
        }
    }
}
```

**Comment by playdual** [comment]
Thank you for your answer.

The intention of Question 1 is, for example, that I want to display the name of the file I selected locally in the inspector.
However, we can display the name of the image by redefining the function of the select button, like the answer in question 3.


Question 2 is only specific components, not all components.


Thank you.

**Comment by BattlehubCode** [comment]
[InitPropertyEditorCallback.unitypackage.zip](https://github.com/user-attachments/files/17291854/InitPropertyEditorCallback.unitypackage.zip)

Hi, I added InitPropertyEditorCallback which will allow you to make changes directly in PropertyEditor of each specific property.

For example:

```
public class MyComponent : MonoBehaviour
{
    public string Text
    {
        get;
        private set;
    }
}
```
```
using Battlehub.RTEditor;
using Battlehub.Utils;
using TMPro;

public class MyComponentDescriptor : ComponentDescriptorBase<MyComponent>
{
    public override PropertyDescriptor[] GetProperties(ComponentEditor editor, object converter)
    {
        return new[]
        {
            new PropertyDescriptor("Str", editor.Components, Strong.MemberInfo((MyComponent x) => x.Text))
            {
                InitPropertyEditorCallback = (sender, args) =>
                {
                    var inputField = args.PropertyEditor.GetComponentInChildren<TMP_InputField>();
                    inputField.interactable = false;
                }
            }
        };
    }
}
```
![telegram-cloud-photo-size-2-5199452628348689897-x](https://github.com/user-attachments/assets/75a6655b-c214-4924-9250-cbcf35e45f66)
