### ISSUE TITLE
Q. Change GameObject Name in Insperctor & Hierachy 

### ISSUE THREAD

**Issue by playdual** [BattlehubCode/RTE_Docs#130]
Hello,
I want to rename an object in the custom component script it has.

For example, when I import an image, I tried to rename the object.

gameObject.name = "Name";
If I make this change, only the Inspector of RTÉ will be changed and HIERACHY will not be changed.

And,
![image](https://github.com/user-attachments/assets/bea2cffb-a4a4-40a2-bebb-42523e063431)
I've tried this method, but Hierachy can't be changed.
The only way Hierachy's name could be changed was if I changed the name directly from Inspector.
And, I would like to know how to access the object in the Hierachy's  window.
Is there any way?

**Comment by BattlehubCode** [comment]
Hi, you can do it using following code:
```
var exposeToEditor = go.GetComponent<ExposeToEditor>();
exposeToEditor.SetName("New Name");
```
