### ISSUE TITLE
save component

### ISSUE THREAD

**Issue by weilifang25** [BattlehubCode/RTE_Docs#134]
I want to save x1 and x4 in the component. How can I do it?
![20241125_220910](https://github.com/user-attachments/assets/fd4bd1d5-9386-43a9-84fe-ead20e79aa3c)

**Comment by BattlehubCode** [comment]
Hi, create surrogate for "MyComponent"
https://github.com/BattlehubCode/RTE_Docs?tab=readme-ov-file#serializer-extensions

or use dynamic surrogate
https://github.com/BattlehubCode/RTE_Docs?tab=readme-ov-file#dynamic-surrogates-preview
